// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEZyEJuLHLczdcQ6PI07txamuhq8Xv7Ys',
    appId: '1:840719378147:web:1de5adf233128955a407d6',
    messagingSenderId: '840719378147',
    projectId: 'potholedetectionapp-320d4',
    authDomain: 'potholedetectionapp-320d4.firebaseapp.com',
    storageBucket: 'potholedetectionapp-320d4.firebasestorage.app',
    measurementId: 'G-NB83RBLBTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4nxCCT71lzqpGLDwG9BV6bmO6vtwFrlY',
    appId: '1:840719378147:android:a7ace3173f2d40a4a407d6',
    messagingSenderId: '840719378147',
    projectId: 'potholedetectionapp-320d4',
    storageBucket: 'potholedetectionapp-320d4.firebasestorage.app',
  );
}